Repository true-tree/true-tree-api, pull requests merged in 2022-07, with the labels that each got.

#10 Feature/multiple databases setting
  .gitignore
  src/main/java/com/truetree/app/domain/coin/dto/response/BitCoinResponseDTO.java
  src/main/java/com/truetree/app/domain/coin/entity/BtcUsdt.java
  src/main/java/com/truetree/app/domain/coin/repository/BitCoinRepository.java
  src/main/java/com/truetree/app/domain/coin/service/BitCoinService.java
  src/main/java/com/truetree/app/domain/main/game/Game.java
  src/main/java/com/truetree/app/domain/main/game/GameHistory.java
  src/main/java/com/truetree/app/domain/main/member/entity/Member.java
  src/main/java/com/truetree/app/domain/main/member/entity/MemberAuthority.java
  src/main/java/com/truetree/app/domain/main/member/entity/MemberAuthorityRepository.java
  src/main/java/com/truetree/app/domain/main/member/entity/MemberRepository.java
  src/main/java/com/truetree/app/domain/main/member/entity/enums/Authority.java
  src/main/java/com/truetree/app/domain/main/member/entity/enums/SocialType.java
  src/main/java/com/truetree/app/domain/main/member/exception/MemberExceptionMessage.java
  src/main/java/com/truetree/app/domain/main/member/service/oauth/MemberService.java
  src/main/java/com/truetree/app/domain/main/member/service/oauth/kakao/KakaoCall.java
  src/main/java/com/truetree/app/domain/main/member/vo/kakao/KakaoAccountVO.java
  src/main/java/com/truetree/app/domain/main/member/vo/kakao/KakaoProfileVO.java
  src/main/java/com/truetree/app/domain/main/member/vo/kakao/KakaoTokenVO.java
  src/main/java/com/truetree/app/domain/member/entity/enums/Authority.java
  src/main/java/com/truetree/app/web/member/controller/MemberAccessController.java
  src/main/java/com/truetree/config/db/HibernateCommonProperties.java
  src/main/java/com/truetree/config/db/PersistenceCoinConfig.java
  src/main/java/com/truetree/config/db/PersistenceMainConfig.java
  src/main/java/com/truetree/config/properties/CoinDbProperties.java
  src/main/java/com/truetree/config/properties/MainDbProperties.java
  src/main/java/com/truetree/config/security/SecurityConfig.java
  src/main/java/com/truetree/config/security/jwt/JwtFilter.java
  src/main/java/com/truetree/config/security/jwt/JwtFilterConfig.java
  src/main/resources/application.yml
  src/test/resources/database.properties
Labels: feature

#11 Server Deploy
  .gitignore
  scripts/deploy.sh
  src/main/java/com/truetree/app/domain/coin/dto/response/BitCoinResponseDTO.java
  src/main/java/com/truetree/app/domain/coin/entity/BtcUsdt.java
  src/main/java/com/truetree/app/domain/coin/repository/BitCoinRepository.java
  src/main/java/com/truetree/app/domain/coin/service/BitCoinService.java
  src/main/java/com/truetree/app/domain/main/game/Game.java
  src/main/java/com/truetree/app/domain/main/game/GameHistory.java
  src/main/java/com/truetree/app/domain/main/member/entity/Member.java
  src/main/java/com/truetree/app/domain/main/member/entity/MemberAuthority.java
  src/main/java/com/truetree/app/domain/main/member/entity/MemberAuthorityRepository.java
  src/main/java/com/truetree/app/domain/main/member/entity/MemberRepository.java
  src/main/java/com/truetree/app/domain/main/member/entity/enums/Authority.java
  src/main/java/com/truetree/app/domain/main/member/entity/enums/SocialType.java
  src/main/java/com/truetree/app/domain/main/member/exception/MemberExceptionMessage.java
  src/main/java/com/truetree/app/domain/main/member/service/oauth/MemberService.java
  src/main/java/com/truetree/app/domain/main/member/service/oauth/kakao/KakaoCall.java
  src/main/java/com/truetree/app/domain/main/member/vo/kakao/KakaoAccountVO.java
  src/main/java/com/truetree/app/domain/main/member/vo/kakao/KakaoProfileVO.java
  src/main/java/com/truetree/app/domain/main/member/vo/kakao/KakaoTokenVO.java
  src/main/java/com/truetree/app/domain/member/entity/enums/Authority.java
  src/main/java/com/truetree/app/web/member/controller/MemberAccessController.java
  src/main/java/com/truetree/config/db/HibernateCommonProperties.java
  src/main/java/com/truetree/config/db/PersistenceCoinConfig.java
  src/main/java/com/truetree/config/db/PersistenceMainConfig.java
  src/main/java/com/truetree/config/properties/CoinDbProperties.java
  src/main/java/com/truetree/config/properties/MainDbProperties.java
  src/main/java/com/truetree/config/security/SecurityConfig.java
  src/main/java/com/truetree/config/security/jwt/JwtFilter.java
  src/main/java/com/truetree/config/security/jwt/JwtFilterConfig.java
  src/main/resources/application.yml
  src/test/resources/database.properties
Labels: deploy

#13 #12 Add Kakao Login By Access Token
  src/main/java/com/truetree/app/domain/main/member/service/oauth/MemberService.java
  src/main/java/com/truetree/app/domain/main/member/service/oauth/kakao/KakaoCall.java
  src/main/java/com/truetree/app/web/member/controller/MemberAccessController.java
  src/main/java/com/truetree/app/web/member/model/request/AccessTokenRequestDTO.java
Labels: feature

#21 Hotfix : 토큰 키값 변경, 닉네임 값 랜덤하게 변경
  src/main/java/com/truetree/app/domain/main/member/vo/kakao/KakaoProfileVO.java
  src/main/java/com/truetree/config/security/jwt/JwtFilter.java
Labels: deploy

#25 Feature/swagger
  build.gradle
  src/main/java/com/truetree/app/web/Game/controller/GameController.java
  src/main/java/com/truetree/app/web/TestController.java
  src/main/java/com/truetree/app/web/member/controller/MemberAccessController.java
  src/main/java/com/truetree/app/web/system/SystemCheckController.java
  src/main/java/com/truetree/config/swagger/SwaggerConfig.java
  src/main/resources/application.properties
Labels: feature

#26 deploy
  build.gradle
  src/main/java/com/truetree/app/web/Game/controller/GameController.java
  src/main/java/com/truetree/app/web/TestController.java
  src/main/java/com/truetree/app/web/member/controller/MemberAccessController.java
  src/main/java/com/truetree/config/swagger/SwaggerConfig.java
  src/main/resources/application.properties
Labels: deploy

#27 Fix : 카카오 로그인시 권한이 중복으로 들어가는 오류 해결
  src/main/java/com/truetree/app/domain/main/member/entity/Member.java
  src/main/java/com/truetree/app/domain/main/member/service/oauth/MemberService.java
  src/main/java/com/truetree/app/domain/main/member/vo/kakao/KakaoProfileVO.java
Labels: refactoring
